using System.Numerics;
using Content.Shared._RMC14.Ghost;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._RMC14.Ghost;

[GenerateTypedNameReferences]
public sealed partial class RMCGhostTargetWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private static readonly Color DarkBackground = Color.FromHex("#151515");
    private static readonly Color ContentBackground = Color.FromHex("#1d1d1d");
    private static readonly Color ChipBorder = Color.FromHex("#2185d0");
    private static readonly Color GreyHeader = Color.FromHex("#6b6b6b");
    private static readonly Color TextMuted = Color.FromHex("#d7d7d7");
    private static readonly Color HealthGood = Color.FromHex("#4b9220");
    private static readonly Color HealthAverage = Color.FromHex("#d9c300");
    private static readonly Color HealthBad = Color.FromHex("#c42026");

    private readonly Dictionary<RMCGhostTargetSection, bool> _collapsedSections = new();
    private readonly Dictionary<string, bool> _collapsedGroups = new();
    private List<RMCGhostTargetSectionModel> _sections = new();
    private string _searchText = string.Empty;
    private bool _loading;
    private SpriteSystem _sprite = default!;

    public event Action<NetEntity>? TargetPressed;
    public event Action? RefreshPressed;
    public event Action? MostFollowedPressed;

    private readonly record struct VisibleGroup(
        RMCGhostTargetGroupModel Group,
        List<RMCGhostTargetButton> Buttons);

    public RMCGhostTargetWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprite = _entityManager.System<SpriteSystem>();

        var searchIconSlot = FindControl<BoxContainer>("SearchIconSlot");
        var mostFollowedSlot = FindControl<BoxContainer>("MostFollowedSlot");
        var refreshSlot = FindControl<BoxContainer>("RefreshSlot");

        AddTextureIcon(searchIconSlot, "/Textures/_RMC14/Interface/search.svg", TextMuted);
        SearchBar.OnTextChanged += OnSearchTextChanged;
        mostFollowedSlot.AddChild(CreateIconButton(
            "/Textures/Interface/Actions/eyeopen.png",
            Loc.GetString("rmc-ghost-target-window-most-followed"),
            () => MostFollowedPressed?.Invoke(),
            HealthGood));
        refreshSlot.AddChild(CreateIconButton(
            "/Textures/Interface/VerbIcons/refresh.svg.192dpi.png",
            Loc.GetString("rmc-ghost-target-window-refresh"),
            () => RefreshPressed?.Invoke(),
            Color.Transparent));
    }

    public void SetLoading()
    {
        _loading = true;
        StatusLabel.Text = Loc.GetString("rmc-ghost-target-window-loading");
        StatusLabel.Visible = true;
        Populate();
    }

    public void UpdateSections(List<RMCGhostTargetSectionModel> sections)
    {
        _sections = sections;
        _loading = false;
        Populate();
    }

    private void Populate()
    {
        SectionsContainer.DisposeAllChildren();

        if (_loading && _sections.Count == 0)
        {
            StatusLabel.Text = Loc.GetString("rmc-ghost-target-window-loading");
            StatusLabel.Visible = true;
            return;
        }

        var sections = new List<RMCGhostTargetSectionModel>(_sections);
        sections.Sort(CompareSections);

        var anyTargets = false;
        foreach (var section in sections)
        {
            var sectionName = Loc.GetString(section.NameLocId);
            var groups = GetVisibleGroups(section, sectionName);
            var visibleCount = CountButtons(groups);
            if (visibleCount == 0)
                continue;

            anyTargets = true;
            AddSection(section, sectionName, groups, visibleCount);
        }

        if (!anyTargets)
        {
            StatusLabel.Text = Loc.GetString(_loading
                ? "rmc-ghost-target-window-loading"
                : "rmc-ghost-target-window-no-targets");
            StatusLabel.Visible = true;
            return;
        }

        StatusLabel.Text = Loc.GetString("rmc-ghost-target-window-loading");
        StatusLabel.Visible = _loading;
    }

    private static int CompareSections(RMCGhostTargetSectionModel left, RMCGhostTargetSectionModel right)
    {
        return left.DisplayOrder.CompareTo(right.DisplayOrder);
    }

    private List<VisibleGroup> GetVisibleGroups(RMCGhostTargetSectionModel section, string sectionName)
    {
        var groups = new List<VisibleGroup>();
        foreach (var group in section.Groups)
        {
            var buttons = new List<RMCGhostTargetButton>();
            foreach (var button in group.Buttons)
            {
                if (IsVisible(button, sectionName, group.Name))
                    buttons.Add(button);
            }

            if (buttons.Count > 0)
                groups.Add(new VisibleGroup(group, buttons));
        }

        return groups;
    }

    private static int CountButtons(List<VisibleGroup> groups)
    {
        var count = 0;
        foreach (var group in groups)
        {
            count += group.Buttons.Count;
        }

        return count;
    }

    private void AddSection(
        RMCGhostTargetSectionModel section,
        string sectionName,
        List<VisibleGroup> groups,
        int visibleCount)
    {
        var collapsed = IsSectionCollapsed(section);
        var headerColor = section.HeaderColor ?? GreyHeader;
        SectionsContainer.AddChild(CreateHeaderButton(
            FormatHeader(collapsed, sectionName, visibleCount),
            headerColor,
            0,
            () =>
            {
                _collapsedSections[section.Section] = !collapsed;
                Populate();
            }));

        if (collapsed)
            return;

        foreach (var group in groups)
        {
            if (!group.Group.ShowHeader)
            {
                AddButtonGrid(group.Buttons, sectionName, group.Group.Name, 18);
                continue;
            }

            var groupKey = GetGroupKey(section.Section, group.Group.Name);
            var groupCollapsed = _collapsedGroups.GetValueOrDefault(groupKey);
            SectionsContainer.AddChild(CreateHeaderButton(
                FormatHeader(groupCollapsed, group.Group.Name, group.Buttons.Count),
                group.Group.HeaderColor ?? headerColor,
                18,
                () =>
                {
                    _collapsedGroups[groupKey] = !groupCollapsed;
                    Populate();
                }));

            if (!groupCollapsed)
                AddButtonGrid(group.Buttons, sectionName, group.Group.Name, 28);
        }
    }

    private bool IsSectionCollapsed(RMCGhostTargetSectionModel section)
    {
        if (_collapsedSections.TryGetValue(section.Section, out var collapsed))
            return collapsed;

        return section.HeaderColor == null;
    }

    private static string GetGroupKey(RMCGhostTargetSection section, string groupName)
    {
        return $"{section}:{groupName}";
    }

    private static string FormatHeader(bool collapsed, string title, int count)
    {
        return $"{(collapsed ? ">" : "v")} {title} - ({count})";
    }

    private ContainerButton CreateHeaderButton(string text, Color color, int leftMargin, Action onPressed)
    {
        var button = new ContainerButton
        {
            HorizontalExpand = true,
            MinHeight = 28,
            Margin = new Thickness(leftMargin, 0, 0, 0),
            StyleBoxOverride = CreateFlatStyle(color, color, 0, 8, 4),
        };

        button.AddChild(new Label
        {
            Text = text,
            FontColorOverride = Color.White,
            HorizontalExpand = true,
            ClipText = true,
        });
        button.OnPressed += _ => onPressed();
        return button;
    }

    private void AddButtonGrid(
        List<RMCGhostTargetButton> buttons,
        string sectionName,
        string groupName,
        int leftMargin)
    {
        var grid = new GridContainer
        {
            MaxGridWidth = 430,
            HSeparationOverride = 4,
            VSeparationOverride = 4,
            Margin = new Thickness(leftMargin, 2, 0, 4),
            HorizontalExpand = true,
        };

        foreach (var button in buttons)
        {
            grid.AddChild(CreateTargetButton(button, sectionName, groupName));
        }

        SectionsContainer.AddChild(grid);
    }

    private Control CreateTargetButton(RMCGhostTargetButton target, string sectionName, string groupName)
    {
        var button = new ContainerButton
        {
            StyleBoxOverride = CreateFlatStyle(DarkBackground, ChipBorder, 1, 7, 3),
            ToolTip = BuildTooltip(target, sectionName, groupName),
            MinHeight = 26,
        };
        button.OnPressed += _ => TargetPressed?.Invoke(target.Entity);

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 4,
            VerticalAlignment = VAlignment.Center,
        };

        if (target.HealthPercent is { } health)
            row.AddChild(CreateColorSquare(GetHealthColor(health)));

        AddIcon(row, target.Background, target.BackgroundColor);
        AddIcon(row, target.Icon, null);

        row.AddChild(new Label
        {
            Text = target.Label,
            FontColorOverride = Color.White,
            ClipText = false,
        });

        if (target.Orbiters > 0)
        {
            AddTextureIcon(row, "/Textures/Effects/crayondecals.rsi/ghost.png", null);
            row.AddChild(new Label
            {
                Text = target.Orbiters.ToString(),
                FontColorOverride = Color.White,
            });
        }

        button.AddChild(row);
        return button;
    }

    private ContainerButton CreateIconButton(string texture, string tooltip, Action onPressed, Color background)
    {
        var button = new ContainerButton
        {
            ToolTip = tooltip,
            MinSize = new Vector2(28, 24),
            StyleBoxOverride = CreateFlatStyle(background, background == Color.Transparent ? ContentBackground : background, 1, 4, 3),
        };
        button.OnPressed += _ => onPressed();

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
        };
        AddTextureIcon(row, texture, background == Color.Transparent ? TextMuted : Color.White);
        button.AddChild(row);
        return button;
    }

    private Control CreateColorSquare(Color color)
    {
        return new PanelContainer
        {
            MinSize = new Vector2(16, 16),
            PanelOverride = CreateFlatStyle(color, color, 0, 0, 0),
        };
    }

    private void AddIcon(BoxContainer row, SpriteSpecifier.Rsi? icon, Color? color)
    {
        if (icon == null)
            return;

        var rect = new TextureRect
        {
            MinSize = new Vector2(16, 16),
            SetSize = new Vector2(16, 16),
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            MouseFilter = MouseFilterMode.Ignore,
            Texture = _sprite.Frame0(icon),
            ModulateSelfOverride = color,
        };

        row.AddChild(rect);
    }

    private void AddTextureIcon(BoxContainer row, string texture, Color? color)
    {
        var rect = new TextureRect
        {
            MinSize = new Vector2(16, 16),
            SetSize = new Vector2(16, 16),
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            MouseFilter = MouseFilterMode.Ignore,
            Texture = _sprite.Frame0(new SpriteSpecifier.Texture(new ResPath(texture))),
            ModulateSelfOverride = color,
        };

        row.AddChild(rect);
    }

    private static StyleBoxFlat CreateFlatStyle(
        Color background,
        Color border,
        int borderThickness,
        int horizontalPadding,
        int verticalPadding)
    {
        var style = new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new Thickness(borderThickness),
        };
        style.SetContentMarginOverride(StyleBox.Margin.Horizontal, horizontalPadding);
        style.SetContentMarginOverride(StyleBox.Margin.Vertical, verticalPadding);
        return style;
    }

    private bool IsVisible(RMCGhostTargetButton target, string sectionName, string groupName)
    {
        if (string.IsNullOrWhiteSpace(_searchText))
            return true;

        return ContainsSearch(target.SearchText) ||
               ContainsSearch(sectionName) ||
               ContainsSearch(groupName);
    }

    private bool ContainsSearch(string? text)
    {
        return text?.Contains(_searchText, StringComparison.OrdinalIgnoreCase) == true;
    }

    private string BuildTooltip(RMCGhostTargetButton target, string sectionName, string groupName)
    {
        var lines = new List<string>
        {
            target.Label,
            sectionName,
        };

        if (!string.IsNullOrWhiteSpace(groupName))
            lines.Add(groupName);

        lines.Add(GetStateText(target));

        if (target.Orbiters > 0)
            lines.Add(Loc.GetString("rmc-ghost-target-window-orbiters", ("count", target.Orbiters)));

        return string.Join('\n', lines);
    }

    private string GetStateText(RMCGhostTargetButton target)
    {
        return target.HealthPercent is { } health
            ? Loc.GetString(GetStateLocId(target.State), ("health", health))
            : Loc.GetString(GetStateLocId(target.State));
    }

    private static Color GetHealthColor(int health)
    {
        if (health > 69)
            return HealthGood;

        if (health > 19)
            return HealthAverage;

        return HealthBad;
    }

    private static string GetStateLocId(RMCGhostTargetState state)
    {
        return state switch
        {
            RMCGhostTargetState.Alive => "rmc-ghost-target-state-alive",
            RMCGhostTargetState.Critical => "rmc-ghost-target-state-critical",
            RMCGhostTargetState.Dead => "rmc-ghost-target-state-dead",
            RMCGhostTargetState.Ghost => "rmc-ghost-target-state-ghost",
            RMCGhostTargetState.Location => "rmc-ghost-target-state-location",
            _ => "rmc-ghost-target-state-unknown",
        };
    }

    private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        _searchText = args.Text.Trim();
        Populate();
        TargetsScroll.SetScrollValue(Vector2.Zero);
    }
}
