using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Lua;

[GenerateTypedNameReferences]
public sealed partial class LuaScriptWindow : FancyWindow
{
    public LuaScriptWindow()
    {
        RobustXamlLoader.Load(this);
        OutputDisplay.Editable = false;
    }
}
