using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Megaphone;

[GenerateTypedNameReferences]
public sealed partial class MegaphoneWindow : DefaultWindow
{
    public MegaphoneWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
